# Generated by Django 6.0 on 2025-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDCOE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('premium', models.IntegerField()),
                ('quota', models.IntegerField()),
                ('bids_received', models.IntegerField()),
                ('pqp', models.IntegerField()),
            ],
        ),
    ]
